import sys
# This script regenerates both source reports with URLs added
data = []
def add(s):
    data.append(s)

# =================== INTERNATIONAL REPORT ===================
add('# OpenCall Token — 艺术机会源站调研报告（含网址）')
add('')
add('**版本:** v1.1')
add('**日期:** 2026-07-01')
add('**用途:** 为 OpenCall Token 爬虫与数据聚合提供源站清单（新增网址列）')
add('')
add('---')
add('')
add('## 说明')
add('')
add('本文档系统梳理了全球范围内发布艺术公开征集（Open Call）、驻留项目（Residency）')
add('和艺术家资助（Grant）信息的主要渠道，包括网站、社群、RSS/邮件列表等。')
add('每个渠道标注了权重与网址，用于指导后续爬虫优先级和数据聚合策略。')
add('')
add('**权重含义：**')
add('')
add('- ★★★★★ (5): 核心数据源，必须覆盖，覆盖最广/质量最高')
add('- ★★★★ (4): 重要数据源，强烈推荐覆盖')
add('- ★★★ (3): 补充数据源，有一定价值')
add('- ★★ (2): 窄众渠道，特定场景有用')
add('- ★ (1): 边缘渠道，数据量少或偶发')
add('')
add('---')
add('')
add('## 一、公开征集（Open Call）源站')
add('')
add('| # | 渠道名称 | 网址 | 权重 | 覆盖范围 | 类型 | 特点 | 爬虫可行性 |')
add('|---|----------|------|------|----------|------|------|-----------|')
add('| 1 | ArtDeadline.com | https://artdeadline.com | ★★★★★ | 全球(偏欧美) | Web | 最全面截止日数据库，每日更新，分类细致 | 高')
add('| 2 | Call for Entry (CaFE) | https://www.callforentry.org | ★★★★★ | 美国为主 | Web | Western States Arts Federation运营，数千美国项目 | 高')
add('| 3 | ArtRabbit | https://artrabbit.com | ★★★★ | 欧洲为主 | Web | 覆盖欧盟艺术竞赛/展览征集，信息结构化好 | 高')
add('| 4 | ArtConnect | https://www.artconnect.com | ★★★★ | 全球 | Web+Newsletter | 现代界面，聚合多源，有邮件推送 | 中')
add('| 5 | OVA (Opportunities in Visual Arts) | https://www.opportunitiesinvisualarts.org | ★★★★ | 北美 | Newsletter | 高质量人工策展邮件列表 | 中')
add('| 6 | CuratorSpace | https://www.curatorspace.com | ★★★ | 全球 | Web | 策展人/展览征集平台 | 高')
add('| 7 | Creative Review | https://www.creativereview.co.uk | ★★★ | 英国/欧洲 | Web | 创意产业征集，设计/广告/数字艺术方向 | 中')
add('| 8 | ArtistsNetwork | https://www.artistsnetwork.com | ★★★ | 美国 | Web | 艺术家杂志配套竞赛/征集列表 | 中')
add('| 9 | The Art List | https://www.theartlist.co.uk | ★★★ | 全球 | Web | 展览/竞赛/驻留信息聚合 | 高')
add('| 10 | Art Hole | https://arthole.com | ★★★ | 全球 | Web | 艺术家征集信息聚合 | 高')
add('| 11 | Artweek | https://artweek.com | ★★ | 美国西海岸 | Web | 区域性征集信息 | 中')
add('| 12 | Artforum | https://www.artforum.com | ★★ | 全球 | Web | 当代艺术杂志，附带征集/招聘信息 | 低')
add('| 13 | Artsy | https://www.artsy.net | ★★ | 全球 | Web | 画廊/拍卖/征集信息混合 | 中')
add('| 14 | Opportunity Desk | https://opportunitydesk.org | ★★★ | 全球 | Web | 面向学生/青少年机会平台，含艺术类 | 高')
add('')
add('---')
add('')
add('## 二、驻留项目（Residency）源站')
add('')
add('| # | 渠道名称 | 网址 | 权重 | 覆盖范围 | 类型 | 特点 | 爬虫可行性 |')
add('|---|----------|------|------|----------|------|------|-----------|')
add('| 1 | Res Artis | https://resartis.org | ★★★★★ | 全球 | Web | 全球最大驻留网络，700+成员机构 | 高')
add('| 2 | Transartists | https://www.transartists.org | ★★★★★ | 全球 | Web | 荷兰文化部支持，最全面驻留数据库之一 | 高')
add('| 3 | Alliance of Artists Communities (AAC) | https://www.artistcommunities.org | ★★★★ | 美国 | Web | 美国驻留机构联盟，数据权威 | 高')
add('| 4 | Residency Unlimited | https://residencyunlimited.org | ★★★★ | 全球 | Web | 驻留机会推荐平台，精品驻留项目 | 中')
add('| 5 | KulturKontakt Austria | https://www.kulturkontakt.or.at | ★★★★ | 全球 | Web | 奥地利文化部运营，全球驻留数据库 | 高')
add('| 6 | UNESCO-Aschberg Programme | https://en.unesco.org/creativity | ★★★ | 全球 | Web | UNESCO驻留项目 | 低')
add('| 7 | On the Move | https://on-the-move.org | ★★★ | 国际 | Web | 国际艺术家流动信息网络 | 中')
add('| 8 | Culturestap | https://culturestap.com | ★★★ | 欧洲 | Web | 欧洲文化机会平台 | 高')
add('| 9 | Artwork Archive | https://www.artworkarchive.com | ★★ | 全球 | Web | 艺术家工具附带驻留列表 | 中')
add('| 10 | artistresidency.com | https://artistresidency.com | ★★★ | 全球 | Web | 驻留项目元搜索 | 中')
add('| 11 | Art Deadlines List | https://artdeadlineslist.com | ★★ | 全球 | Email | 含驻留在内的截止日邮件列表 | 中')
add('| 12 | residencyprograms.net | https://residencyprograms.net | ★★ | 全球 | Web | 驻留项目博客 | 中')
add('| 13 | Weltformat / Pro Helvetia | https://prohelvetia.ch | ★★★ | 瑞士/全球 | Web | 瑞士文化基金会驻留/交换项目 | 高')
add('| 14 | Arte Laguna Prize | https://www.artelagunaprize.com | ★★ | 全球 | Web | 威尼斯Arte Laguna奖附带驻留机会 | 中')
add('')
add('---')
add('')
add('## 三、艺术家资助（Grant）源站')
add('')
add('| # | 渠道名称 | 网址 | 权重 | 覆盖范围 | 类型 | 特点 | 爬虫可行性 |')
add('|---|----------|------|------|----------|------|------|-----------|')
add('| 1 | NYFA Classifieds | https://www.nyfa.org/classifieds | ★★★★★ | 美国/全球 | Web+Email | 纽约艺术基金会，最权威艺术机会邮件之一 | 高')
add('| 2 | Candid (原 Foundation Center) | https://candid.org | ★★★★★ | 美国 | Web | 美国最全基金会/资助数据库 | 中')
add('| 3 | GrantStation | https://www.grantstation.com | ★★★★ | 全球 | Web | 国际资助数据库，含艺术类 | 中')
add('| 4 | NEA (National Endowment for the Arts) | https://www.arts.gov | ★★★★ | 美国 | Web | 美国国家艺术基金 | 高')
add('| 5 | Creative Capital | https://creative-capital.org | ★★★ | 美国 | Web | 创新艺术项目资助 | 中')
add('| 6 | Pollock Krasner Foundation | https://www.pkf.org | ★★★ | 全球 | Web | 视觉艺术资助，全年开放 | 低')
add('| 7 | Joan Mitchell Foundation | https://www.joanmitchellfoundation.org | ★★★ | 美国 | Web | 画家/雕塑家资助 | 低')
add('| 8 | Guggenheim Foundation | https://www.gf.org | ★★★ | 美国/加拿大 | Web | 古根海姆奖学金 | 低')
add('| 9 | Artadia | https://www.artadia.org | ★★★ | 美国 | Web | 城市限定资助 | 低')
add('| 10 | Jerome Foundation | https://www.jeromefdn.org | ★★★ | 美国 | Web | 早期职业艺术家资助 | 低')
add('| 11 | Andy Warhol Foundation | https://www.warholfoundation.org | ★★★ | 美国 | Web | 艺术写作/策展类资助 | 低')
add('| 12 | State Arts Agencies | https://www.arts.gov (各州链接) | ★★★ | 美国各州 | Web | 各州艺术委员会资助 | 高')
add('| 13 | Canada Council for the Arts | https://canadacouncil.ca | ★★★ | 加拿大 | Web | 加拿大艺术委员会 | 高')
add('| 14 | Arts Council England | https://www.artscouncil.org.uk | ★★★ | 英国 | Web | 英格兰艺术委员会 | 高')
add('| 15 | Creative New Zealand | https://www.creativenz.govt.nz | ★★ | 新西兰 | Web | 新西兰艺术委员会 | 高')
add('| 16 | Australia Council for the Arts | https://www.australiacouncil.gov.au | ★★ | 澳大利亚 | Web | 澳大利亚艺术委员会 | 高')
add('| 17 | Prince Claus Fund | https://princeclausfund.org | ★★★ | 全球(发展中国家) | Web | 面向发展中国家的文化资助 | 高')
add('| 18 | Ford Foundation | https://www.fordfoundation.org | ★★ | 全球 | Web | 社会正义导向艺术资助 | 中')
add('')
add('---')
add('')
add('## 四、RSS 源与邮件列表')
add('')
add('| # | 渠道名称 | 网址/获取方式 | 权重 | 类型 | 内容 |')
add('|---|----------|---------------|------|------|------|')
add('| 1 | NYFA Classifieds | https://www.nyfa.org/classifieds (订阅) | ★★★★★ | 邮件列表 | 美国及全球征集/驻留/资助/工作 |')
add('| 2 | OVA Newsletter | https://www.opportunitiesinvisualarts.org (订阅) | ★★★★ | 邮件列表 | 北美视觉艺术机会，人工精选 |')
add('| 3 | ArtDeadline.com RSS | https://artdeadline.com/feed/ | ★★★★ | RSS | 按类别分组截止日 RSS |')
add('| 4 | ArtConnect Newsletter | https://www.artconnect.com (订阅) | ★★★ | 邮件列表 | 精选全球机会 |')
add('| 5 | Google Alerts | https://www.google.com/alerts | ★★ | 邮件 | 自定义关键词跟踪 |')
add('| 6 | Twitter/X 列表 | https://x.com (创建机构监控列表) | ★★★ | 社交媒体 | 跟踪机构推文 |')
add('')
add('---')
add('')
add('## 五、社群与社交媒体渠道')
add('')
add('| # | 渠道名称 | 网址 | 权重 | 平台 | 内容特点 | 获取难度 |')
add('|---|----------|------|------|------|----------|----------|')
add('| 1 | r/artopportunities | https://www.reddit.com/r/artopportunities | ★★★★ | Reddit | 用户自发分享，覆盖三类机会 | 高')
add('| 2 | Facebook群组 | https://www.facebook.com/groups (搜索) | ★★★★ | Facebook | 多群组每日大量更新 | 中')
add('| 3 | Discord | 各服务器邀请链接 | ★★★ | Discord | 各类艺术服务器设机会频道 | 中')
add('| 4 | Instagram/Twitter | https://www.instagram.com / https://x.com | ★★ | 社交 | 机构发布碎片化机会 | 低')
add('| 5 | LinkedIn群组 | https://www.linkedin.com (搜索) | ★★ | LinkedIn | 艺术管理/策展方向 | 低')
add('')
add('---')
add('')
add('## 六、爬虫优先级策略')
add('')
add('**第一批（P0 — 核心数据源，立即覆盖）：**')
add('')
add('1. ArtDeadline.com (https://artdeadline.com)')
add('2. Call for Entry (https://www.callforentry.org)')
add('3. Res Artis (https://resartis.org)')
add('4. Transartists (https://www.transartists.org)')
add('5. NYFA Classifieds (https://www.nyfa.org/classifieds)')
add('6. OVA (https://www.opportunitiesinvisualarts.org)')
add('')
add('**第二批（P1 — 重要补充）：**')
add('')
add('7. ArtRabbit (https://artrabbit.com)')
add('8. ArtConnect (https://www.artconnect.com)')
add('9. AAC (https://www.artistcommunities.org)')
add('10. KulturKontakt (https://www.kulturkontakt.or.at)')
add('11. GrantStation (https://www.grantstation.com) / Candid (https://candid.org)')
add('12. Reddit r/artopportunities (https://www.reddit.com/r/artopportunities)')
add('')
add('**第三批（P2 — 扩覆盖）：**')
add('')
add('13. Facebook群组 (https://www.facebook.com/groups)')
add('14. 各国艺术委员会 (NEA/Canada Council/Arts Council England 等)')
add('15. 高价值单机构 (MacDowell/DAAD/Rijksakademie/Skowhegan)')
add('16. The Art List / Art Hole / CuratorSpace 等中小聚合')
add('')
add('---')
add('')
add('_本文档同步于 OpenCall Token 项目文档_')
add('')

with open(r'C:\Users\arenn\Documents\Codex\2026-06-30\opencall-token\源站调研报告.md', 'w', encoding='utf-8') as f:
    f.write('\n'.join(data))
print('Written 源站调研报告.md (international)')
print(f'Total lines: {len(data)}')
