import sys

lines = []
def add(s):
    lines.append(s)

add('# OpenCall Token — 艺术机会源站调研报告')
add('')
add('**版本:** v1.0')
add('**日期:** 2026-07-01')
add('**用途:** 为 OpenCall Token 爬虫与数据聚合提供源站清单')
add('')
add('---')
add('')
add('## 说明')
add('')
add('本文档系统梳理了全球范围内发布艺术公开征集（Open Call）、驻留项目（Residency）')
add('和艺术家资助（Grant）信息的主要渠道，包括网站、社群、RSS/邮件列表等。')
add('每个渠道标注了权重，用于指导后续爬虫优先级和数据聚合策略。')
add('')
add('**权重含义：**')
add('')
add('- ★★★★★ (5): 核心数据源，必须覆盖，覆盖最广/质量最高')
add('- ★★★★☆ (4): 重要数据源，强烈推荐覆盖')
add('- ★★★☆☆ (3): 补充数据源，有一定价值')
add('- ★★☆☆☆ (2): 窄众渠道，特定场景有用')
add('- ★☆☆☆☆ (1): 边缘渠道，数据量少或偶发')
add('')
add('---')
add('')
add('## 一、公开征集（Open Call）源站')
add('')
add('| # | 渠道名称 | 权重 | 覆盖范围 | 类型 | 特点 | 爬虫可行性 |')
add('|---|----------|------|----------|------|------|-----------|')
add('| 1 | **ArtDeadline.com** | ★★★★★ | 全球（偏欧美） | Web | 最全面的艺术截止日数据库，每日更新，分类细致 | 高 -- 结构化列表页 |')
add('| 2 | **Call for Entry (CaFE)** | ★★★★★ | 美国为主 | Web | Western States Arts Federation 运营，数千个美国征集项目 | 高 -- 搜索页面清晰 |')
add('| 3 | **ArtRabbit** | ★★★★ | 欧洲为主 | Web | 覆盖欧盟艺术竞赛/展览征集，信息结构化好 | 高 -- 结构化数据 |')
add('| 4 | **ArtConnect** | ★★★★ | 全球 | Web + Newsletter | 现代界面，聚合多源，有邮件推送 | 中 -- 需注册部分功能 |')
add('| 5 | **OVA (Opportunities in Visual Arts)** | ★★★★ | 北美 | Newsletter | 高质量人工策展邮件列表，每周推送 | 中 -- 邮件列表为主 |')
add('| 6 | **CuratorSpace** | ★★★ | 全球 | Web | 策展人/展览征集平台 | 高 -- 分类清晰 |')
add('| 7 | **Creative Review** | ★★★ | 英国/欧洲 | Web | 创意产业征集，设计/广告/数字艺术方向 | 中 -- 非结构化为主 |')
add('| 8 | **ArtistsNetwork** | ★★★ | 美国 | Web | 艺术家杂志配套的竞赛/征集列表 | 中 -- 页面较传统 |')
add('| 9 | **The Art List** | ★★★ | 全球 | Web | 展览/竞赛/驻留信息聚合 | 高 -- 列表结构清晰 |')
add('| 10 | **Art Hole** | ★★★ | 全球 | Web | 艺术家征集信息聚合 | 高 -- 简洁列表 |')
add('| 11 | **Artweek** | ★★ | 美国西海岸 | Web | 区域性征集信息 | 中 -- 区域有限 |')
add('| 12 | **Artforum** | ★★ | 全球 | Web | 当代艺术杂志，附带征集/招聘信息 | 低 -- 非结构化，分散 |')
add('| 13 | **Artsy** | ★★ | 全球 | Web | 画廊/拍卖/征集信息混合 | 中 -- 需筛选 |')
add('| 14 | **Opportunity Desk** | ★★★ | 全球 | Web | 面向学生/青年的机会平台，含艺术类 | 高 -- 列表清晰 |')
add('')
add('---')
add('')
add('## 二、驻留项目（Residency）源站')
add('')
add('| # | 渠道名称 | 权重 | 覆盖范围 | 类型 | 特点 | 爬虫可行性 |')
add('|---|----------|------|----------|------|------|-----------|')
add('| 1 | **Res Artis** | ★★★★★ | 全球 | Web | 全球最大驻留网络，700+ 成员机构，数据库历史最久 | 高 -- 结构化数据库 |')
add('| 2 | **Transartists** | ★★★★★ | 全球 | Web | 荷兰文化部支持，全球最全面的驻留数据库之一 | 高 -- 分类筛选完善 |')
add('| 3 | **Alliance of Artists Communities (AAC)** | ★★★★ | 美国 | Web | 美国驻留机构联盟，会员制，数据权威 | 高 -- 机构目录清晰 |')
add('| 4 | **Residency Unlimited** | ★★★★ | 全球 | Web | 驻留机会推荐平台，覆盖精品驻留项目 | 中 -- 少量/精选模式 |')
add('| 5 | **KulturKontakt Austria** | ★★★★ | 全球 | Web | 奥地利文化部运营，全球驻留数据库 | 高 -- 结构化数据 |')
add('| 6 | **UNESCO-Aschberg Programme** | ★★★ | 全球 | Web | UNESCO驻留项目，权威但数量少 | 低 -- 更新频率低 |')
add('| 7 | **On the Move** | ★★★ | 国际 | Web | 国际艺术家流动信息网络 | 中 -- 资讯为主 |')
add('| 8 | **Culturestap** | ★★★ | 欧洲 | Web | 欧洲文化机会平台 | 高 -- 结构化列表 |')
add('| 9 | **Artwork Archive** | ★★ | 全球 | Web | 艺术家工具附带驻留列表 | 中 -- 次級内容 |')
add('| 10 | **artistresidency.com** | ★★★ | 全球 | Web | 驻留项目元搜索 | 中 -- 聚合搜索 |')
add('| 11 | **Art Deadlines List** | ★★ | 全球 | Email | 包含驻留在内的截止日邮件列表 | 中 -- 邮件为主 |')
add('| 12 | **residencyprograms.net** | ★★ | 全球 | Web | 驻留项目博客 | 中 -- 博客格式 |')
add('| 13 | **Weltformat / Pro Helvetia** | ★★★ | 瑞士/全球 | Web | 瑞士文化基金会，驻留/交换项目 | 高 -- 结构清楚 |')
add('| 14 | **Arte Laguna Prize** | ★★ | 全球 | Web | 威尼斯Arte Laguna奖附带驻留机会 | 中 -- 单一项目 |')
add('')
add('---')
add('')
add('## 三、艺术家资助（Grant）源站')
add('')
add('| # | 渠道名称 | 权重 | 覆盖范围 | 类型 | 特点 | 爬虫可行性 |')
add('|---|----------|------|----------|------|------|-----------|')
add('| 1 | **NYFA Classifieds** | ★★★★★ | 美国/全球 | Web + Email | 纽约艺术基金会，最权威的艺术机会邮件列表之一 | 高 -- 分类清晰 |')
add('| 2 | **Candid (原 Foundation Center)** | ★★★★★ | 美国 | Web | 美国最全的基金会/资助数据库 | 中 -- 部分需登录 |')
add('| 3 | **GrantStation** | ★★★★ | 全球 | Web | 国际资助数据库，含艺术类资助 | 中 -- 付费功能居多 |')
add('| 4 | **NEA (National Endowment for the Arts)** | ★★★★ | 美国 | Web | 美国国家艺术基金，政府资助 | 高 -- 官方结构清晰 |')
add('| 5 | **Creative Capital** | ★★★ | 美国 | Web | 创新艺术项目资助 | 中 -- 项目制 |')
add('| 6 | **Pollock Krasner Foundation** | ★★★ | 全球 | Web | 视觉艺术资助，全年开放 | 低 -- 单一基金会 |')
add('| 7 | **Joan Mitchell Foundation** | ★★★ | 美国 | Web | 画家/雕塑家资助 | 低 -- 单一基金会 |')
add('| 8 | **Guggenheim Foundation** | ★★★ | 美国/加拿大 | Web | 古根海姆奖学金 | 低 -- 单一项目 |')
add('| 9 | **Artadia** | ★★★ | 美国 | Web | 城市限定资助（纽约/洛杉矶/芝加哥等） | 低 -- 地域限制 |')
add('| 10 | **Jerome Foundation** | ★★★ | 美国 | Web | 早期职业艺术家资助 | 低 -- 地域限制 |')
add('| 11 | **Andy Warhol Foundation** | ★★★ | 美国 | Web | 艺术写作/策展类资助 | 低 -- 方向窄 |')
add('| 12 | **State Arts Agencies (各州艺术委员会)** | ★★★ | 美国各州 | Web | 各州艺术委员会资助汇总 | 高 -- 各州官网 |')
add('| 13 | **Canada Council for the Arts** | ★★★ | 加拿大 | Web | 加拿大艺术委员会资助 | 高 -- 官方 |')
add('| 14 | **Arts Council England** | ★★★ | 英国 | Web | 英格兰艺术委员会 | 高 -- 官方 |')
add('| 15 | **Creative New Zealand** | ★★ | 新西兰 | Web | 新西兰艺术委员会 | 高 -- 官方 |')
add('| 16 | **Australia Council for the Arts** | ★★ | 澳大利亚 | Web | 澳大利亚艺术委员会 | 高 -- 官方 |')
add('| 17 | **Prince Claus Fund** | ★★★ | 全球（发展中国家） | Web | 面向发展中国家的文化与艺术资助 | 高 -- 结构清晰 |')
add('| 18 | **Ford Foundation** | ★★ | 全球 | Web | 社会正义导向的艺术资助 | 中 -- 非专用页面 |')
add('')
add('---')
add('')
add('## 四、RSS 源与邮件列表')
add('')
add('| # | 渠道名称 | 权重 | 类型 | 内容 | 获取方式 |')
add('|---|----------|------|------|------|----------|')
add('| 1 | **NYFA Classifieds** | ★★★★★ | 邮件列表 | 美国及全球征集/驻留/资助/工作 | 订阅 weekly 邮件 |')
add('| 2 | **OVA Newsletter** | ★★★★ | 邮件列表 | 北美视觉艺术机会，人工精选 | 订阅邮件 |')
add('| 3 | **ArtDeadline.com RSS** | ★★★★ | RSS | 按类别分组的截止日 RSS 源 | RSS Feed |')
add('| 4 | **ArtConnect Newsletter** | ★★★ | 邮件列表 | 精选全球机会 | 订阅邮件 |')
add('| 5 | **Google Alerts** | ★★ | 邮件 | 自定义关键词跟踪 | Google Alerts 配置 |')
add('| 6 | **Twitter/X Lists** | ★★★ | 社交媒体 | 可跟踪大批机构推文 | API 或 RSS Bridge |')
add('')
add('---')
add('')
add('## 五、社群与社交媒体渠道')
add('')
add('| # | 渠道名称 | 权重 | 平台 | 内容特点 | 获取难度 |')
add('|---|----------|------|------|----------|----------|')
add('| 1 | **r/artopportunities** | ★★★★ | Reddit | 用户自发分享，覆盖三类机会，更新活跃 | 高 -- Reddit API |')
add('| 2 | **Facebook 艺术机会群组** | ★★★★ | Facebook | 多群组共生，每日大量更新 | 中 -- 需群组爬取 |')
add('| 3 | **Discord 艺术服务器** | ★★★ | Discord | 各类服务器设机会频道 | 中 -- 需加入 |')
add('| 4 | **Instagram / Twitter** | ★★ | 社交媒体 | 机构发布碎片化机会 | 低 -- 难批量 |')
add('| 5 | **LinkedIn 群组** | ★★ | LinkedIn | 艺术管理/策展方向 | 低 -- 活跃度一般 |')
add('')
add('---')
add('')
add('## 六、爬虫优先级策略')
add('')
add('**第一批（P0 -- 核心数据源，立即覆盖）：**')
add('')
add('1. ArtDeadline.com -- 覆盖最广的截止日数据库')
add('2. Call for Entry (CaFE) -- 美国征集主阵地')
add('3. Res Artis -- 全球驻留第一数据库')
add('4. Transartists -- 全球驻留第二数据库（互补）')
add('5. NYFA Classifieds -- 美国/全球资助与机会')
add('6. OVA Newsletter -- 北美精选人工策展')
add('')
add('**第二批（P1 -- 重要补充）：**')
add('')
add('7. ArtRabbit -- 欧洲征集')
add('8. ArtConnect -- 聚合多源机会')
add('9. Alliance of Artists Communities -- 美国驻留网络')
add('10. KulturKontakt Austria -- 全球驻留补充')
add('11. GrantStation / Candid -- 资助数据库')
add('12. Reddit r/artopportunities -- 社群补充')
add('')
add('**第三批（P2 -- 扩覆盖）：**')
add('')
add('13. Facebook 相关群组 (3-5 个核心群)')
add('14. 各国艺术委员会 (NEA/Canada Council/Arts Council England)')
add('15. 高价值单机构 (MacDowell/DAAD/Rijksakademie/Skowhegan)')
add('16. The Art List / Art Hole / CuratorSpace 等中小聚合')
add('')
add('---')
add('')
add('_本文档同步于 OpenCall Token 项目文档_')
add('')

with open(r'C:\Users\arenn\Documents\Codex\2026-06-30\opencall-token\源站调研报告.md', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f'Written {len(lines)} lines to 源站调研报告.md')
